/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,jsx}"],
  theme: {
    colors: {
      primary: "#0D247F",
      primaryLight: "#0D247F07",
      dark: "#0D1426",
      iconGray: "#E4E6F0",
      listBlue: "#EBEDF7",
      textGray: "#C4C6D3",
      darkBlue: "#0D247F",
      default: "#E6E7E8",
      defaultLight: "#E6E7E807",
      danger: "#DD2D2D",
      dangerLight: "#DD2D2D07",
      dangerLight: "#DD2D2D07",
      warning: "#FFAC32",
      warningLight: "#FFAC3207",
      success: "#14AD5B",
      successLight: "#14AD5B07",
      info: "#4099D9",
      infoLight: "#4099D907",
      white: "#FFFFFF",
      indigo: "#7D8AC9",
      gray01: "#FEFEFE",
      gray1: "#F2F3F4",
      gray2: "#AAADB6",
      gray3: "#757986",
      gray4: "#656565",
    },
    extend: {},
  },
  purge: {
    options: {
      safelist: [
        "btn-primary",
        "btn-success",
        "btn-info",
        "btn-danger",
        "btn-default",
        "btn-outline-primary",
        "btn-outline-success",
        "btn-outline-info",
        "btn-outline-danger",
        "small",
        "medium",
        "large",
        "text-small",
        "text-medium",
        "text-large",
        "text-primary",
        "text-info",
        "text-danger",
        "text-success",
        "text-indigo",
        "font-bold",
        "font-normal",
        "title-h1",
        "title-h2",
        "title-h3",
        "title-h4",
        "title-h5",
        "title-h6",
        "bg-primary",
        "bg-default",
        "bg-info",
        "bg-success",
        "bg-danger",
        "bg-indigo",
      ],
    },
  },
  plugins: [],
};
